version: '2'
services:
  db:
    extends:
      file: template.yml
      service: db

  redis:
    extends:
      file: template.yml
      service: redis

  node:
    extends:
      file: template.yml
      service: node
    ports:
      - '300${i}:3000'
    env_file:
      - config/docker/node${i}.env

  sidekiq:
    extends:
      file: template.yml
      service: sidekiq
    env_file:
      - config/docker/node${i}.env
